import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/_styles/globals.css';

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: {
    template: '%s | Todoist',
    default: 'Todoist | A To-Do List to Organize Your Work & Life',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-background-200 text-gray-1000 flex flex-col antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
